-- SA Recruiters — Talent Pool email alerts (free MVP)
-- Run this once in the Supabase SQL Editor before enabling alerts.

alter table public.pool_candidates
  add column if not exists email_alert_opt_in boolean not null default false,
  add column if not exists alert_sectors text,
  add column if not exists alert_locations text,
  add column if not exists alert_consent_at timestamptz,
  add column if not exists alert_unsubscribe_token text;

create unique index if not exists pool_candidates_alert_unsubscribe_token_idx
  on public.pool_candidates(alert_unsubscribe_token)
  where alert_unsubscribe_token is not null;

create table if not exists public.vacancy_alert_queue (
  id bigint generated by default as identity primary key,
  vacancy_id text not null,
  candidate_id text not null,
  recipient_email text not null,
  status text not null default 'queued' check (status in ('queued','sent','failed','unsubscribed')),
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  error_message text,
  unique (vacancy_id, candidate_id)
);

create index if not exists vacancy_alert_queue_status_idx
  on public.vacancy_alert_queue(status, created_at);

alter table public.vacancy_alert_queue enable row level security;

-- The public app can only create/read alert preferences through the existing
-- pool registration flow. Queue rows are intended for the authenticated admin.
-- Do not add an anonymous insert policy for the queue.

drop function if exists public.unsubscribe_pool_email_alerts(text);
create or replace function public.unsubscribe_pool_email_alerts(p_token text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.pool_candidates
     set email_alert_opt_in = false,
         alert_consent_at = null
   where alert_unsubscribe_token = p_token
     and alert_unsubscribe_token is not null;
  return found;
end;
$$;

revoke all on function public.unsubscribe_pool_email_alerts(text) from public;
grant execute on function public.unsubscribe_pool_email_alerts(text) to anon, authenticated;

-- EmailJS template requirements for the current low-volume MVP:
-- To: {{to_email}}
-- Subject: New SA Recruiters vacancy: {{vacancy_title}}
-- Body should include {{to_name}}, {{company}}, {{location}}, {{apply_link}},
-- and an unsubscribe URL using the deployed site's ?unsubscribe={{unsubscribe_token}}.
-- For higher volume, replace the browser-side sender with a server-side provider.
