-- Manual WhatsApp Channel queue.
-- The browser never reads these tables directly; the admin-only Worker uses
-- the Supabase service role after verifying the signed-in admin.

CREATE TABLE IF NOT EXISTS public.whatsapp_queue_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slot_key text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'posted', 'archived')),
  post_text text NOT NULL DEFAULT '',
  selected_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  posted_at timestamptz,
  posted_by uuid REFERENCES auth.users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.whatsapp_queue_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id uuid NOT NULL REFERENCES public.whatsapp_queue_batches(id) ON DELETE CASCADE,
  vacancy_id text NOT NULL REFERENCES public.vacancies(id) ON DELETE CASCADE,
  position integer NOT NULL CHECK (position BETWEEN 1 AND 5),
  title text NOT NULL DEFAULT '',
  company text NOT NULL DEFAULT '',
  location text NOT NULL DEFAULT '',
  public_url text NOT NULL DEFAULT '',
  application_url text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'copied', 'posted', 'skipped')),
  created_at timestamptz NOT NULL DEFAULT now(),
  copied_at timestamptz,
  posted_at timestamptz,
  notes text,
  UNIQUE (batch_id, vacancy_id)
);

CREATE INDEX IF NOT EXISTS whatsapp_queue_batches_created_idx
  ON public.whatsapp_queue_batches (created_at DESC);
CREATE INDEX IF NOT EXISTS whatsapp_queue_items_batch_idx
  ON public.whatsapp_queue_items (batch_id, position);
CREATE INDEX IF NOT EXISTS whatsapp_queue_items_vacancy_idx
  ON public.whatsapp_queue_items (vacancy_id, created_at DESC);

ALTER TABLE public.whatsapp_queue_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_queue_items ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE public.whatsapp_queue_batches IS
  'Admin-generated hourly batches of five vacancies prepared for manual WhatsApp Channel posting.';
COMMENT ON TABLE public.whatsapp_queue_items IS
  'The five vacancy links and copy state belonging to a WhatsApp queue batch.';

GRANT ALL ON public.whatsapp_queue_batches TO service_role;
GRANT ALL ON public.whatsapp_queue_items TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.whatsapp_queue_items_id_seq TO service_role;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'whatsapp_queue_batches'
      AND policyname = 'service role manages whatsapp queue batches'
  ) THEN
    CREATE POLICY "service role manages whatsapp queue batches"
      ON public.whatsapp_queue_batches FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'whatsapp_queue_items'
      AND policyname = 'service role manages whatsapp queue items'
  ) THEN
    CREATE POLICY "service role manages whatsapp queue items"
      ON public.whatsapp_queue_items FOR ALL TO service_role
      USING (true) WITH CHECK (true);
  END IF;
END $$;

-- Keep the public/anon roles out of the queue even if future broad policies
-- are added to neighbouring tables.
REVOKE ALL ON public.whatsapp_queue_batches FROM anon, authenticated;
REVOKE ALL ON public.whatsapp_queue_items FROM anon, authenticated;
-- Verification:
-- SELECT table_name FROM information_schema.tables
-- WHERE table_schema = 'public' AND table_name LIKE 'whatsapp_queue%';
